### ISSUE TITLE
Extension does not load

### ISSUE THREAD

**Issue by mfilej** [greneholt/youtube5#35] opened 2013-06-26 08:35 UTC
Not sure if this is the right place to report issues, but here it goes.

I've been seeing this problem since yesterday: the youtube5 extension seems to load at the beginning, being visible for a second or so, but gets quickly replaced by the default youtube html5 player. For videos that require flash, the message "Flash player is required for playback" appears (I don't have flash on my system).

**Comment by ggustafsson** [comment] 2013-07-12 03:33
Duplicate of #32 and #33. No solution exist yet :'(

**Comment by greneholt** [comment] 2013-07-18 05:44
This is fixed in v2.6.2

**Closed as completed by greneholt** 2013-07-18 05:44 UTC

**Comment by mfilej** [comment] 2013-07-18 09:10
Awesome, thank you so much!
