### ISSUE TITLE
Preview image is broken on Feedly

### ISSUE THREAD

**Issue by ggustafsson** [greneholt/youtube5#36] opened 2013-07-12 03:43 UTC
All the YouTube videos i've seen so can be played on Feedly (feedly.com) but the preview is always messed up. I don't know if you take a look at it or not but that's how it is. Picture included:

![screen shot 2013-07-12 at 05 39 54](https://f.cloud.github.com/assets/595501/786238/0bffa422-eaa5-11e2-8d5f-0469b8200323.png)

It looks pretty similar on every feed containing a video.

**Comment by greneholt** [comment] 2013-09-16 17:20
I finally looked into this, and determined it is caused by Feedly stripping style attributes from the contents of feeds. Fortunately, setting the custom attribute data-clean to yes on the YouTube5 player makes Feedly stop doing this. Fixed in v2.6.6

**Closed as completed by greneholt** 2013-09-16 17:20 UTC

**Comment by ggustafsson** [comment] 2013-09-17 02:20
Thanks! :+1:
