### ISSUE TITLE
Player controls missing

### ISSUE THREAD

**Issue by MacTaipan** [greneholt/youtube5#68] opened 2015-05-01 19:11 UTC
Hi!

For a few days now in Safari 8.0.5 the YouTube5 player control bar below the video ist missing. I can't pause playback or jump in the timeline etc.
It must have happened when I installed the 10.10.3 supplemental update. With the previous 10.10.3 update it worked flawlessly.

**Comment by NalgeNunc** [comment] 2015-05-02 09:08
It's the same over here. OS X 10.5.8 on PPC, Safari 5.0.6 or latest leopard-webkit. No control bar on Youtube videos, while most embedded videos show controls. I think Youtube changed things once again. Thanks for your nice Safari extension.

**Comment by Denus01** [comment] 2015-05-02 10:22
Got the same issue: the controls are gone (Safari 7.1.5 on Mavericks).
There's also a strange overlay, like the movie is not fitting right in place.
I got this problem for a few days or so.

**Comment by Nellio** [comment] 2015-05-02 15:52
Same issue.

Control bar not displayed until the end of the video, and then non functional. “I can't pause, playback, or jump in the timeline, etc.”

Also, YouTube5 information overlay not displaying. Can't select resolution, etc.

(Safari 7.1.5 on Mavericks)

**Comment by samuelkraft** [comment] 2015-05-04 07:16
Temporary fix for this:
Add this bit of CSS with the [User CSS extension](http://code.grid.in.th) for youtube.com/\* :

``` css
.youtube5placeholder {
  position: relative;
  z-index: 9999;
}
```

**Comment by Denus01** [comment] 2015-05-04 10:52
Thanks, will try this.

**Comment by hit-and-run** [comment] 2015-05-04 13:33
Thank you, samuelkraft. It worked for me.

32bit intel SnowLeopard Safari 5.1.10

**Comment by MacTaipan** [comment] 2015-05-04 19:24
That's pretty cool, but it doesn't seem to work 100%. On some videos there's some blank black space added below the navigation bar:

![bildschirmfoto 2015-05-04 um 21 20 17](https://cloud.githubusercontent.com/assets/12202553/7460496/b89c158c-f2a3-11e4-8ff6-6dba3ea199c9.png)

The height of the blank space varies. Perhaps the CSS code resuts in a fixed vertical height of the video frame?

**Comment by Anthracity** [comment] 2015-05-04 19:34
Have the same problem with Safari 8.0.5 under OS X 10.10.3.

**Comment by samuelkraft** [comment] 2015-05-05 06:52
@MacTaipan The height is another issue. The CSS code basically makes sure that the video is always positioned above all other elements.

**Comment by ergl** [comment] 2015-05-09 00:35
~~Hmm, I have another problem that may or may not be related to this one, although I suspect it is.~~

For the last few days I've been unable to click the play button on youtube. I'm running Safari 7.1.5 on Mavericks 10.9.5.

This problem seems to "solve" itself by turning off  'Prevent videos from playing automatically' on the plugin settings.

The video will now play normally, but having the same issues as you guys.

Edit: Yep, it's the same issue, adding the css rule that @samuelkraft suggested seems to solve the play button issue too.

**Comment by Nellio** [comment] 2015-05-10 13:18
Samuel Kraft's proposed CSS fix does work. Thanks!

**Comment by modingo** [comment] 2015-05-12 08:04
I'm using a mac with OS X10.8.5 and just updated to Safari 6.2.6 tonight.  The YouTube5 v2.6.8 Safari extension has been installed for awhile with no issues until this latest Safari update.  The YouTube video control bar is now missing.  If this extension is enabled, the video window shows only a black rectangle along the window where the video controls should be.  Mouse clicking in the area where the controls once were does nothing.  After troubleshooting my 6 extensions (2 of which were already disabled), I found the issue was caused by a conflict with YouTube5 v2.6.8.  The conflicting extension is currently installed but now disabled and there are no issues now.

**Comment by MacTaipan** [comment] 2015-05-12 15:08
Can you tell us which extension it was? I get the problem even when only YouTube5 and ClickToPlugin are activated. But when I deactivate ClickToPlugin, YouTube5 doesn't kick in in the first play, because YouTube's own HTML 5 player is used instead.

**Comment by caveman1973** [comment] 2015-08-06 22:24
I tried the CSS fix and it solved the problem BUT:

When I increase the size of the player on Youtube (not fullscreen), the Youtube (search) Topbar on top is visible. Is there a solution?

**Comment by hit-and-run** [comment] 2015-11-12 02:25
Dang. Finally stopped working properly. This time it seems that the default youtube player starts playing a video behind Youtube5's player. So the User CSS extension fix won't do it.
I thought about fixing it myself, but you can't even debug an extension unless you buy Apple Developer Program membership.
Is anyone even still using this extension? I love this.

32 bit intel, SnowLeopard, Safari 5.1.10

**Comment by greneholt** [comment] 2015-11-12 16:57
I officially ended development on YouTube5 a few months ago. You can [read more here](http://www.verticalforest.com/2015/08/22/ending-development-of-youtube5/).

**Closed as completed by greneholt** 2015-11-12 16:57 UTC

**Comment by samuelkraft** [comment] 2015-11-13 08:20
For those looking for an alternative, [ClickToPlugin](https://hoyois.github.io/safariextensions/clicktoplugin/) essentially does the same thing. It replaces youtube's html5 player with the native/default html5 player. On el capitan the native html5 player is a lot faster than before and has built in support for airplay, is responsive etc.
https://github.com/hoyois/clicktoplugin

<img width="896" alt="screen shot 2015-11-13 at 09 11 07" src="https://cloud.githubusercontent.com/assets/2223418/11141598/177f6f56-89e7-11e5-8b94-9fba7f3f0233.png">
